Repository ianshulx/DSA-Programs, pull requests merged in 2022-10, with the labels that each got.

#44 Create binarysearch.cpp
  binarysearch.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#47 added a famous interview question on recursion
  letters_combination_of_phone_number.cpp
Labels: question, hacktoberfest, hacktoberfest-accepted

#48 Create middle_node_of_linked_list.cpp
  middle_node_of_linked_list.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#49 Create merge_two_sorted_lists.cpp
  merge_two_sorted_lists.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#50 Create is_list_palindrome.cpp
  is_list_palindrome.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#54 Create delete_last_occurence_linked_list.cpp
  delete_last_occurence_linked_list.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#53 Create merge_sort_for_linked_list.cpp
  merge_sort_for_linked_list.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#52 Create detectLoopList.cpp
  detectLoopList.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#51 Create pairwise_swap_nodes.cpp
  pairwise_swap_nodes.cpp
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#58 added deleting middle element using stack
  Interview problems in C++/deletion of middle element using stacks.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#57 Create Maximum of all subarrays of size k.java
  Data Structure problems using Java/Maximum of all subarrays of size k.java
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#61 Create linear search.cpp
  searching in c++/linear search.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#59 3-Sum problem
  Data Structure Problems using java/4-sum.java
  Data Structure Problems using java/Find a triplet with the given sum in an array.java
  Maximum Product Subarray Problem.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#64 Array Rotation.cpp
  Interview problems in C++/ArrayRotation.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#65 Create Jump Search.cpp
  searching in c++/Jump Search.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#67 Create Ternary Search.cpp
  searching in c++/Ternary Search.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#68 Create pascals_triangle.cpp
  Dynamic Programming/pascals_triangle.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#66 Added Stack Programs In C++
  Ford-Fulkerson Algorithm.cpp
  Stack/INFIX TO POSTFIX.txt
  Stack/Next  greater element.txt
  Stack/StackUsingArray.cpp
  Stack/Stock span problem.txt
  Stack/The celebrity problem.txt
  Stack/maximum rectangular area in a histogram.txt
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#70 Added Longest Common Sequence.cpp
  Longest Common Subsequence.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#71 Create Interpolation Search.cpp
  searching in c++/Interpolation Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#72 Create Exponential Search.cpp
  searching in c++/Exponential Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#73 Bubble sort and selection sort in java with minimum complexity
  Sorting algorithm using java/bubbleSort.java
  Sorting algorithm using java/selectionSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#74 Added Binary Tree Traversal.cpp
  Binary_Tree_Traversal-inorder.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#78 Added Circular Linked List.cpp
  CircularLinkedList.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#79 Largest BST Subtree
  array rotation.cpp
  largest bst subtree.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#80 Create SieveOfEratosthenes.java
  SieveOfEratosthenes.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#84 Create SIEVE OF ERATOSTHENES.java
  Data Structure Problems using java/SIEVE OF ERATOSTHENES.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#87 title: Ford-Fulkerson Algorithm for Maximum Flow Problem
  C++ Algorithms/Convex Hull - Graham Scan/Output.txt
  C++ Algorithms/Convex Hull - Graham Scan/main.cpp
  C++ Algorithms/Dinic’s algorithm for Maximum Flow/Output.txt
  C++ Algorithms/Dinic’s algorithm for Maximum Flow/main.cpp
  C++ Algorithms/Ford-Fulkerson Algorithm for Maximum Flow Problem/Output.txt
  C++ Algorithms/Ford-Fulkerson Algorithm for Maximum Flow Problem/main.cpp
Labels: good first issue, question, hacktoberfest, hacktoberfest-accepted

#89 Added graph algos
  Graph Algorithms/Articulation Points (or Cut Vertices) in a Graph using Tarjan’s Algorithm.cpp
  Graph Algorithms/Bridges in a graph using DFS traversal.cpp
  Graph Algorithms/Kruskal’s MST algo.cpp
  Graph Algorithms/Topological Sorting.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#92 Create Unique Paths II.cpp
  Graph Algorithms/Unique Paths II.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#93 Populating Next Right Pointers in Each Node.cpp
  116. Populating Next Right Pointers in Each Node
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#97 Candy.cpp
  135. Candy
Labels: hacktoberfest, hacktoberfest2022

#102 Floyd Warshall Algorithm
  Graph Algorithms/Floyd Warshall Algorithm
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#112 String Matching
  string_matching.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#114 Added Zeroes_to_end.cpp
  maximum_sum_subArray.cpp
  zeroestoend.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#113 added sum and largest nodes of tree.cpp
  tree1.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#115 Create 3. Longest Substring Without Repeating Characters.java
  Data Structures problems using Java/3. Longest Substring Without Repeating Characters.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#121 StrandSort.cpp
  Sorting algorithms in C++/StrandSort.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#117 Added Bellman-Ford Algorithm
  Graph Algorithms/Bellman-Ford Algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#116 Added DP program on Longest Common Subsequence
  Dynamic Programming/longestCommonSubsequence.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#125 added dsa using java
  Data Structure Problems using java/RemoveDuplicates.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#124 Added Quicksort Algorithm
  QuickSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#126 Added opp datastructure for car battery
  battery check electric car oop datastructure.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#136 String To Integer , Implementing Atoi function in cpp
  String_To_Integer.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#131 Kruskal's algorithm in java
  Data Structure Problems using java/Graph.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#137 Quick sort in java
  Sorting algorithm using java/QuickSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#133 Added Solution to Move Zeroes question
  Interview problems in C++/Move Zeroes.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#132 Added solution to String to Integer question.
  Interview problems in C++/String to Integer.cpp
Labels: hacktoberfest, hacktoberfest2022

#143 Update Binary Search(GFG).cpp
  Interview problems in C++/Binary Search(GFG).cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#148 Odd Even Sorting Algorithm
  odd_even_algo.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#160 A* Search Algorithm in C++
  searching in c++/A-start-search-algorithm/Graphs.cpp
  searching in c++/A-start-search-algorithm/Graphs.sln
  searching in c++/A-start-search-algorithm/Graphs.vcxproj
  searching in c++/A-start-search-algorithm/Graphs.vcxproj.filters
  searching in c++/A-start-search-algorithm/vector.cpp
  searching in c++/A-start-search-algorithm/vector.h
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#158 Added two important programs in DSA in java
  AVLTree.java
  BelmannFord.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#168 Create Clone a linked list with next and random pointer.cpp
  Clone a linked list with next and random pointer.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#166 Added dynamic programming solution
  Dynamic Programming/Grid-Unique-Paths.cpp
  Dynamic Programming/Hose-Robber-II.cpp
  Dynamic Programming/Matrix-Chain-Multiplication.cpp
  Dynamic Programming/Maximum-Sum-of-Non-Adjacent-Elements.cpp
  Dynamic Programming/Ninjas-Training.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#171 added allocating min number of pages
  Interview problems in C++/allocating_minimum_number_of_pages.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#176 Create Stacks using Java
  Data Structure Problems using java/Stacks using Java
Labels: hacktoberfest, hacktoberfest-accepted

#200 Create MaxNonAdjacentSum.c++
  Popular DSA problem in C++/MaxNonAdjacentSum.c++
Labels: hacktoberfest, hacktoberfest-accepted

#199 Create ReversalLinkedList.c++
  Popular DSA problem in C++/ReversalLinkedList.c++
Labels: hacktoberfest, hacktoberfest-accepted

#198 Create MinMax.c++
  Popular DSA problem in C++/MinMax.c++
Labels: hacktoberfest, hacktoberfest-accepted

#197 Create Spiral.c++
  Popular DSA problem in C++/Spiral.c++
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#196 Contributed with Linear Search implementation in CPP
  Linear_Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#180 Create Binary search.cpp
  searching in c++/Binary search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#201 Create Contains-Duplicate-2.cpp
  Interview problems in C++/Contains-Duplicate-2.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#195 Create string.cpp
  string.cpp
Labels: hacktoberfest

#194 add notAbubakar to the contributers list
  fibonacci.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#193 hash table in c++ that works
  Data Structures using C/Hash_Tables.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#190 Create maxProductSubset.cpp
  maxProductSubset.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#188 Create minProductSubset.cpp
  minProductSubset.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#205 Create CelsiusToFahrenheit.cpp
  CelsiusToFahrenheit.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#208 Added Code for 2 Sum
  2sum.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#219 Dutch National Flag Algorithm
  C++ Algorithms/dutchflag.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#216 CONTRIBUTING.MD
  CONTRIBUTING.MD
Labels: hacktoberfest

#221 Adding N-Queens.cpp
  Recurrsion in C++/N-Queens.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#224 C++ codes for buy and sell stock - 1,2,3
  Best time to buy and sell stock I.cpp
  Best time to buy and sell stock II.cpp
  Best time to buy and sell stock III.cpp
  Dynamic Programming/Super Egg drop.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
